### PR TITLE
Add typings

### PR DESCRIPTION
**Pull request by stramel**
Provides typings to TypeScript users.

I based all text and definition off the documentation in the README.md file.

### CODE REVIEW

**Comment by stramel** [comment]
Ping @jsonmaur

**Comment by jsonmaur** [comment]
Excellent, I've been meaning to do this. Thanks @stramel!

**Comment by stramel** [comment]
You're welcome! Thanks for the merge.

**Comment by jsonmaur** [comment]
Released with v1.1.3.

**Pull request merged**
